.ci/release.yml
.ci/windows-release.yml
README.md
azure-pipelines.yml

Badges updated and credit to Grin added in README.md
Azure Pipeline config updated. It _should_:
- Run tests on new commits or PRs
- Build and release on new tags (with sha256sums)
- Include Windows, Ubuntu, and OS X
- Produce full backtraces on errors

README tweaks and CI config

---

doc/roadmap.md

---
title: ''
labels: ''
assignees: ''
---
* Updates …

Organization and formatting.

---

doc/roadmap.md

---
title: ''
labels: ''
assignees: ''
---
* Updates …

Buyer and Hodler Priority

---

core/src/consensus.rs

A hard fork proof of work change to remove C32 and C33 from activating along with some other changes to strengthen the network. These have been extensively tested in unit tests and on Floonet. Planned implementation will be by updating the developer node, the mining pools, any exchanges and other users.
Because of the consistent and relentless malicious miner attacks, that have only grown in severity and sophistication, we feel these are important changes for the viability and strength of the MWC network. There has been significant discussion and consensus among the largest MWC holders, miners and developers regarding these changes.
All major stakeholders are in agreement with these changes to strengthen the network. The major stakeholders thought it would be appropriate that I, as the …

Proof of Work Hard Fork

---

doc/roadmap.md

---
title: ''
labels: ''
assignees: ''
---
* Updates …

Update HODL Program and Fork Policy

---

doc/exchange_recommendations.md

---
title: ''
labels: ''
assignees: ''
---
* Updates …

Deposit and Withdrawal Suggestions

---

doc/roadmap.md

---
title: ''
labels: ''
assignees: ''
---
* Updates …

Ossification

---

doc/roadmap.md

---
title: ''
labels: ''
assignees: ''
---
* Updates …

Formatting

---

doc/roadmap.md

---
title: ''
labels: ''
assignees: ''
---
* Updates …

No soft fork.

---

doc/roadmap.md

---
title: ''
labels: ''
assignees: ''
---
* Updates …

HODL Program Distributed

---

doc/roadmap.md

Added dates and software versions for the timeline of completed steps.
---
title: ''
labels: ''
assignees: ''
---
* …

Update for timeline

---

p2p/src/serv.rs

Fix bug of https://github.com/mwcproject/mwc-node/issues/26

fix the p2p self address and port

---

chain/src/chain.rs
chain/src/error.rs
config/src/config.rs
core/src/core/transaction.rs
servers/src/common/types.rs
servers/src/grin/server.rs

Cherry-pick from Grin and adapt the hash for MWC.
* rewind prior to known bad block on chain init
* rewind prior to bad block if found on current chain
* pass InvalidBlockProof through

Rewind bad block

---

etc/Dockerfile

Current Dockerfile was empty, so I created one. Built successfully on my docker host & running it now.

feat: Implemented Dockerfile

---

etc/Dockerfile

fixes:
- Ncurses not showing properly
- Tor binary added, so tor will work
User Interface was showing weird characters instead of proper Ncurses interface. Happened both in KiTTY/PuTTY as connectbot on Android. Fixed now.
Container started and exited when tor binary was not added, now it works:

fix: Ncurses interface not working properly in Docker container + added Tor support

---

core/src/libtx/aggsig.rs

This PR implements the simplified form of the 2-key signatures described as "batch" signatures in the paper [Non-interactive Mimblewimble transactions, revisited](https://eprint.iacr.org/2022/265.pdf).
Matching the paper exactly would require riskier and more complex changes to the underlying C crypto library, so we implement here a simpler version that builds signatures for 2 keys (P1 and P2) that are verifiable against the single public key `P := P1 + H(P1||P2) * P2`. This will give us the same security properties without the need to modify any crypto primitives.
`build_composite_pubkey` was made a separate function so that callers may batch verify 2-key signatures alongside standard single element schnorr sigs using the existing `verify_batch` function.

batch signatures

---

core/src/genesis.rs
doc/mwc_mining_guide.md
keychain/src/extkey_bip32.rs

Update for rust v1.80 build. Mining doc changes

---

chain/src/chain.rs
p2p/src/store.rs
servers/src/common/adapters.rs
servers/src/mwc/seed.rs
servers/src/mwc/sync.rs
servers/src/mwc/sync/body_sync.rs
servers/src/mwc/sync/header_sync.rs
servers/src/mwc/sync/orphans_sync.rs
servers/src/mwc/sync/sync_manager.rs
servers/src/mwc/sync/syncer.rs

Active sync for orphans
Update peers handling logic, added some seed peers into the set to connect with

V5.3.3/sync

---

p2p/src/peers.rs
p2p/src/protocol.rs
p2p/src/serv.rs
p2p/src/store.rs

Fix visualization for inbound connections for tor

Fix inbound connection for tor

---

chain/src/txhashset/desegmenter.rs

debug assert fix. To understand the fix see how the bitmap is updated before. Let's keep bitmap update simple and modify assert instead.

debug assert fix

---

azure-pipelines.yml

updated platform names

---

Cargo.lock
Cargo.toml
api/Cargo.toml
chain/Cargo.toml
chain/src/chain.rs
config/Cargo.toml
core/Cargo.toml
keychain/Cargo.toml
p2p/Cargo.toml
pool/Cargo.toml
servers/Cargo.toml
servers/src/mwc/seed.rs
servers/src/mwc/sync/orphans_sync.rs
store/Cargo.toml
util/Cargo.toml

- Deadlock fix. 
- Fix archive node compact-sync throttling on low end hardware.  
- Every 10 minutes try to add a new peers, so the network will never be static.

V5.3.7/deadlock

---

Cargo.lock
core/src/global.rs

Cargo update, build fix

---

core/src/core/transaction.rs
core/src/libtx/mod.rs

---
title: ''
labels: ''
assignees: ''
---
* Updates …

more functionality to calculate fees for wallet

---

Cargo.lock
Cargo.toml
src/build/build.rs

Upgraded git2 to fix Windows build

---

servers/src/mining/stratum_data.rs

warnings fix
